# Uncomment the next line to define a global platform for your project
# platform :ios, '10.0'

target 'CosTogether' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CosTogether
  pod 'SwiftLint'
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  pod 'Firebase/Storage'
  pod 'FBSDKLoginKit'
  pod 'FSPagerView'
  pod 'IQKeyboardManagerSwift'
  pod 'SDWebImage'
  pod 'NotificationBannerSwift'
  pod 'Fabric'
  pod 'Crashlytics'
  pod 'KeychainAccess'
  pod 'AnimatedCollectionViewLayout'
  pod 'SVProgressHUD'
  pod 'lottie-ios'
  
end
